services:
  - type: web
    name: obti
    runtime: static
    buildCommand: pnpm install --no-frozen-lockfile && pnpm build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
